# Generated by Django 5.0.7 on 2024-08-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('pro_user', 'Can access to books detail.')]},
        ),
    ]
